### PR TITLE
Update to 1.3.5

### PR DESCRIPTION
**Pull request by janisz**

### CODE REVIEW

**Comment by karthimohan** [comment]
Hi Janisx, thanks for the fix. Your change did work after upgrading to Marathon version 1.3.6. However these system endpoints: /v2/leader, /v2/info, /v2/events , /v2/eventSubscriptions was broken and giving 403. We rely on /events endpoint heavily So I had to revert my Marathon upgrade back to 1.1.1. It would be great if you could make this change as well if possible.

**Comment by janisz** [comment]
@karthimohan Can you file an issue for this change?

**Comment by karthimohan** [comment]
@janisz Yes. I did file an issue for this change. https://github.com/mesosphere/marathon-example-plugins/issues/16

**Comment by aquamatthias** [comment]
Thanks!

**Pull request merged**
